/*=====================================================================
  materiallibrary.js – Material library (named material presets)
  ---------------------------------------------------------------
  Generated by the level editor's Materials -> Library tool.
  Apply to a prop via prop.material = "<name>"; the game paints it on
  spawn (PropLevel.applyMaterialPreset). Fields: albedo, opacity,
  emission, emissionIntensity, metalness, roughness, texture, tileX, tileY.
=====================================================================*/

const MaterialLibrary = {
    "Mossy Green": {
        "albedo": "#5f8f3a",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0,
        "roughness": 0.8
    },
    "Glowing Amber": {
        "albedo": "#ffb03a",
        "opacity": 1,
        "emission": "#ff7a00",
        "emissionIntensity": 1.2,
        "metalness": 0,
        "roughness": 0.5
    },
    "Wet Stone": {
        "albedo": "#9aa3ad",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0.1,
        "roughness": 0.35
    },
    "Light Brown": {
        "albedo": "#7e664f",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 1,
        "metalness": 0,
        "roughness": 1
    },
    "Wood Brown": {
        "albedo": "#7e664f",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 1,
        "metalness": 0,
        "roughness": 1,
        "texture": "wood-texture.jpg",
        "tileX": 2,
        "tileY": 1
    },
    "Rose Wood": {
        "albedo": "#1f1405",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 1,
        "metalness": 0,
        "roughness": 1,
        "texture": "wood-texture.jpg",
        "tileX": 1,
        "tileY": 1
    },
    "Concrete Gray": {
        "albedo": "#cdd0d2",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0,
        "roughness": 0.95
    },
    "Apartment Marble Wall": {
        "albedo": "#909498",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0,
        "roughness": 0.85,
        "texture": "marble-wall-texture.jpg",
        "tileX": 2,
        "tileY": 2
    },
    "Apartment Concrete Floor": {
        "albedo": "#c2c2c2",
        "opacity": 1,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0,
        "roughness": 0.95,
        "texture": "concrete-texture.jpg",
        "tileX": 3,
        "tileY": 3
    },
    "Invisible Collider": {
        "albedo": "#808080",
        "opacity": 0,
        "emission": "#000000",
        "emissionIntensity": 0,
        "metalness": 0,
        "roughness": 1
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MaterialLibrary };
}
