/*=====================================================================
  materiallibrary.js – Material library (named material presets)
  ---------------------------------------------------------------
  Generated by the level editor's Materials → 📚 Library tool
  ("Save to Library" + "Export materiallibrary.js"). Each entry is a
  named surface look you can apply to a prop; a level file then stores
  the choice as `prop.material = "<name>"` (see PropLevel.exportProp),
  and the game paints it on spawn (PropLevel.applyMaterialPreset).

  Fields (all optional):
    albedo            hex string   – base colour tint (multiplies the map)
    opacity           0..1
    emission          hex string   – glow colour ("#000000" = none)
    emissionIntensity 0..3
    metalness         0..1         – PBR/GLB materials only
    roughness         0..1         – PBR/GLB materials only
    texture           filename in assets/textures/  – map (omit = keep model's)
    tileX, tileY      texture repeat (with texture)

  Replace the object below with the editor's exported JSON to update it.
=====================================================================*/

const MaterialLibrary = {
    "Mossy Green": {
        albedo: "#5f8f3a", opacity: 1,
        emission: "#000000", emissionIntensity: 0,
        metalness: 0, roughness: 0.8
    },
    "Glowing Amber": {
        albedo: "#ffb03a", opacity: 1,
        emission: "#ff7a00", emissionIntensity: 1.2,
        metalness: 0, roughness: 0.5
    },
    "Wet Stone": {
        albedo: "#9aa3ad", opacity: 1,
        emission: "#000000", emissionIntensity: 0,
        metalness: 0.1, roughness: 0.35
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MaterialLibrary };
}
