/*=====================================================================
  prefabs.js – Prefab library (Unity-style prop type defaults)
  ---------------------------------------------------------------
  Generated by the level editor's "Edit Prefabs" tool.
  Each prop TYPE defines its gameplay defaults (collision, climbable,
  hideSpot, canDisguise) and an optional compound `colliders` template
  (per piece: shape + position/rotation/scale, fractions of the prop bounds).
=====================================================================*/

const PrefabLibrary = {
  "tree": {
      "collision": true,
      "climbable": true,
      "hideSpot": false,
      "canDisguise": true,
      "colliders": [
          {
              "shape": "cylinder",
              "position": {
                  "x": 0,
                  "y": 0.275,
                  "z": 0
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.18,
                  "y": 0.55,
                  "z": 0.18
              }
          },
          {
              "shape": "cylinder",
              "position": {
                  "x": 0,
                  "y": 0.75,
                  "z": 0
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.95,
                  "y": 0.5,
                  "z": 0.95
              }
          }
      ]
  },
  "rock": {
      "collision": true,
      "climbable": true,
      "hideSpot": true,
      "canDisguise": true,
      "colliders": [
          {
              "shape": "box",
              "position": {
                  "x": 0.053,
                  "y": 0.447,
                  "z": -0.117
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.607,
                  "y": 0.776,
                  "z": 0.639
              }
          }
      ]
  },
  "bush": {
      "collision": true,
      "climbable": true,
      "hideSpot": true,
      "canDisguise": true
  },
  "wall": {
      "collision": true,
      "climbable": true,
      "hideSpot": false,
      "canDisguise": false,
      "colliderShape": "box"
  },
  "spawn": {
      "collision": false,
      "climbable": false,
      "hideSpot": false,
      "canDisguise": false
  }
};

const PREFAB_DEFAULT = {
  "collision": true,
  "climbable": false,
  "hideSpot": false,
  "canDisguise": false
};

// The local player's own collider (NOT a prop — absolute world units).
//   radius  horizontal collision radius of the undisguised player
//   height  eye/center height above the feet (PLAYER_BASE_HEIGHT); the full
//           standing body is 2× this. Drives the camera height, climbing, and
//           the undisguised movement collision. A disguised hider instead adopts
//           its prop's collider, so this only applies in player form.
const PlayerCollider = {
  "radius": 1,
  "height": 1.5
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PrefabLibrary, PREFAB_DEFAULT, PlayerCollider };
}
