/*=====================================================================
  prefabs.js – Prefab library (Unity-style prop type defaults)
  ---------------------------------------------------------------
  Generated by the level editor's "Edit Prefabs" tool.
  Each prop TYPE defines its gameplay defaults (collision, climbable,
  hideSpot, canDisguise) and an optional compound `colliders` template
  (per piece: shape + position/rotation/scale, fractions of the prop bounds).
  PlayerCollider = the local player's own collider (radius + eye/center height,
  absolute world units; full body = 2× height).
=====================================================================*/

const PrefabLibrary = {
  "tree": {
      "collision": true,
      "climbable": true,
      "hideSpot": false,
      "canDisguise": true,
      "colliders": [
          {
              "shape": "cylinder",
              "position": {
                  "x": 0,
                  "y": 0.307,
                  "z": 0
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.18,
                  "y": 0.838,
                  "z": 0.18
              }
          },
          {
              "shape": "cylinder",
              "position": {
                  "x": 0,
                  "y": 0.814,
                  "z": 0
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.95,
                  "y": 0.223,
                  "z": 0.95
              }
          }
      ]
  },
  "rock": {
      "collision": true,
      "climbable": true,
      "hideSpot": true,
      "canDisguise": true,
      "colliders": [
          {
              "shape": "box",
              "position": {
                  "x": 0.053,
                  "y": 0.447,
                  "z": -0.117
              },
              "rotation": {
                  "y": 0
              },
              "scale": {
                  "x": 0.607,
                  "y": 0.776,
                  "z": 0.639
              }
          }
      ]
  },
  "bush": {
      "collision": true,
      "climbable": true,
      "hideSpot": true,
      "canDisguise": true
  },
  "wall": {
      "collision": true,
      "climbable": true,
      "hideSpot": false,
      "canDisguise": false,
      "colliderShape": "box"
  },
  "spawn": {
      "collision": false,
      "climbable": false,
      "hideSpot": false,
      "canDisguise": false
  }
};

const PREFAB_DEFAULT = {
  "collision": true,
  "climbable": false,
  "hideSpot": false,
  "canDisguise": false
};

const PlayerCollider = {
  "radius": 0.7,
  "height": 1.5
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PrefabLibrary, PREFAB_DEFAULT, PlayerCollider };
}
