/*=====================================================================
  prefabs.js – Prefab library (Unity-style prop type defaults)
  ---------------------------------------------------------------
  Generated by the level editor's "Edit Prefabs" tool.
  Each prop TYPE defines its gameplay defaults (collision, climbable,
  hideSpot, canDisguise) and an optional compound `colliders` template
  (per piece: shape + position/rotation/scale, fractions of the prop bounds).
  PlayerCollider = the local player's own collider (radius + eye/center height,
  absolute world units; full body = 2× height).
=====================================================================*/

const PrefabLibrary = {
    "tree": {
        "collision": true,
        "climbable": true,
        "hideSpot": false,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "box",
                "position": {
                    "x": 0,
                    "y": 0.754,
                    "z": 0.032
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.401,
                    "y": 0.286,
                    "z": 0.828
                }
            },
            {
                "shape": "box",
                "position": {
                    "x": -0.024,
                    "y": 0.324,
                    "z": -0.136
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.036,
                    "y": 0.592,
                    "z": 0.06
                }
            }
        ]
    },
    "rock": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "box",
                "position": {
                    "x": 0.053,
                    "y": 0.447,
                    "z": -0.117
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.607,
                    "y": 0.776,
                    "z": 0.639
                }
            }
        ]
    },
    "bush": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "cylinder",
                "position": {
                    "x": 0,
                    "y": 0.468,
                    "z": 0
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.765,
                    "y": 0.808,
                    "z": 1
                }
            }
        ]
    },
    "wall": {
        "collision": true,
        "climbable": true,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    },
    "cube": {
        "collision": true,
        "climbable": true,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    },
    "spawn": {
        "collision": false,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false
    },
    "barrel": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "cylinder",
                "position": {
                    "x": 0,
                    "y": 0.5,
                    "z": 0
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.864,
                    "y": 0.912,
                    "z": 1
                }
            }
        ]
    },
    "crate": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliderShape": "box"
    },
    "pot": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "cylinder",
                "position": {
                    "x": -0.232,
                    "y": 0.628,
                    "z": -0.072
                },
                "rotation": {
                    "y": 0
                },
                "scale": {
                    "x": 0.512,
                    "y": 0.64,
                    "z": 1
                }
            }
        ]
    },
    "cart": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true,
        "colliderShape": "box"
    },
    "rock2": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true
    },
    "bush2": {
        "collision": false,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true
    },
    "bush3": {
        "collision": false,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true
    },
    "fence": {
        "collision": true,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    },
    "steps": {
        "collision": true,
        "climbable": true,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box",
        "colliders": [
            {
                "shape": "box",
                "position": {
                    "x": 0,
                    "y": 0.28,
                    "z": 0.09
                },
                "rotation": {
                    "x": -148.373,
                    "y": 0,
                    "z": -180
                },
                "scale": {
                    "x": 0.993,
                    "y": 0.184,
                    "z": 0.648
                }
            },
            {
                "shape": "box",
                "position": {
                    "x": 0,
                    "y": 0.326,
                    "z": -0.517
                },
                "rotation": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                },
                "scale": {
                    "x": 0.992,
                    "y": 0.711,
                    "z": 0.121
                }
            }
        ]
    },
    "entrance": {
        "collision": false,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false
    },
    "amphora": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true
    },
    "fruitcrate": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliderShape": "box"
    },
    "hay": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true
    },
    "sack": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true,
        "colliders": [
            {
                "shape": "box",
                "position": {
                    "x": 0,
                    "y": 0.444,
                    "z": 0
                },
                "rotation": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                },
                "scale": {
                    "x": 0.851,
                    "y": 0.769,
                    "z": 0.5
                }
            }
        ]
    },
    "sackpile": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true
    },
    "table": {
        "collision": true,
        "climbable": true,
        "hideSpot": true,
        "canDisguise": true,
        "colliderShape": "box"
    },
    "tent": {
        "collision": false,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false
    },
    "lamppost": {
        "collision": true,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false
    },
    "hut": {
        "collision": true,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    },
    "house": {
        "collision": true,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    },
    "door": {
        "collision": false,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false
    },
    "cupboard": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true,
        "colliderShape": "box"
    },
    "chair": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true
    },
    "bucket": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true
    },
    "books": {
        "collision": true,
        "climbable": false,
        "hideSpot": true,
        "canDisguise": true
    },
    "pillar": {
        "collision": true,
        "climbable": false,
        "hideSpot": false,
        "canDisguise": false,
        "colliderShape": "box"
    }
};

const PREFAB_DEFAULT = {
    "collision": true,
    "climbable": false,
    "hideSpot": false,
    "canDisguise": false
};

const PlayerCollider = {
    "radius": 0.7,
    "height": 1.5
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { PrefabLibrary, PREFAB_DEFAULT, PlayerCollider };
}
